name: gladstoriesengine
description: The library for the Glad Stories Engine. This is an interactive fiction engine which can be used for editing and running your stories.
homepage: https://github.com/gladimdim/gladstoriesdart

version: 0.3.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart: ^0.26.0

dev_dependencies:
  test: ^1.15.0